//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibraryManagement.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFine
    {
        public int ID { get; set; }
        public Nullable<int> Member { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<int> Move { get; set; }
    
        public virtual TblMove TblMove { get; set; }
        public virtual TblMember TblMember { get; set; }
    }
}
